/**
 * Created by zhangchi on 2014/8/14.
 */
var reels1=[["P4","K","N","P4"],["P2","A","N","P3"],["Q","P1","J","P1"],["S","K","P2","P2"],["A","P4","J","P1"]]
var reels2=[["P3","P4","P3","P2"],["W","N","K","A"],["P1","P2","T","P4"],["P3","A","P2","P3"],["A","K","P3","P2"]]
var reels3=[["P2","T","P1","P3"],["P2","P1","N","K"],["P3","T","K","P2"],["S","N","P3","P1"],["P2","N","P4","T"]]
var reels4=[["A","T","Q","P3"],["A","Q","N","K"],["P3","T","Q","A"],["S","N","P3","A"],["W","N","P2","T"]]
var reels5=[["S","T","Q","P3"],["A","S","N","K"],["P3","S","Q","A"],["P1","N","T","A"],["W","N","P2","T"]]
var g_fakeData=[
    //free spin
    {
        Reels:reels5,
        Wins:[[{Symbol:"S",Position:[0,0]},{Symbol:"S",Position:[1,1]},{Symbol:"S",Position:[2,1]}]],
        GrossWin:600,
        Anti:2,
        isBonus:true,
        freeSpinRemaining:5
    },

    {
        Reels:reels4,
        Wins:[
            [{Symbol:"A",Position:[0,0]},{Symbol:"A",Position:[1,0]},{Symbol:"A",Position:[2,3]},{Symbol:"A",Position:[3,3]},{Symbol:"W",Position:[4,0]}],
            [{Symbol:"Q",Position:[0,2]},{Symbol:"Q",Position:[1,1]},{Symbol:"Q",Position:[2,2]}]
        ],
        GrossWin:93,
        Anti:0,
        bonusWin:93,
        freeSpinRemaining:4
    },
    {
        Reels:reels3,
        Wins:[
            [{Symbol:"P2",Position:[0,0]},{Symbol:"P2",Position:[1,0]},{Symbol:"P2",Position:[2,3]}],
            [{Symbol:"P1",Position:[0,2]},{Symbol:"P1",Position:[1,1]}]
        ],
        GrossWin:150,
        Anti:0,
        bonusWin:243,
        freeSpinRemaining:3
    },
    {
        Reels:reels2,
        Wins:[
            [{Symbol:"P3",Position:[0,0]},{Symbol:"W",Position:[1,0]}],
            [{Symbol:"P3",Position:[0,2]},{Symbol:"W",Position:[1,0]}],
            [{Symbol:"P4",Position:[0,1]},{Symbol:"W",Position:[1,0]},{Symbol:"P4",Position:[2,3]}],
            [{Symbol:"P2",Position:[0,3]},{Symbol:"W",Position:[1,0]},{Symbol:"P2",Position:[2,1]},{Symbol:"P2",Position:[3,2]},{Symbol:"P2",Position:[4,3]}]
        ],
        GrossWin:400,
        Anti:0,
        bonusWin:643,
        freeSpinRemaining:2
    },
    {
        Reels:reels1,
        Wins:null,
        GrossWin:0,
        Anti:0,
        bonusWin:643,
        freeSpinRemaining:1
    },
    {
        Reels:reels4,
        Wins:[
            [{Symbol:"A",Position:[0,0]},{Symbol:"A",Position:[1,0]},{Symbol:"A",Position:[2,3]},{Symbol:"A",Position:[3,3]},{Symbol:"W",Position:[4,0]}],
            [{Symbol:"Q",Position:[0,2]},{Symbol:"Q",Position:[1,1]},{Symbol:"Q",Position:[2,2]}]
        ],
        GrossWin:93,
        Anti:0,
        bonusWin:736,
        freeSpinRemaining:0
    },
    ////
    {
        Reels:reels4,
        Wins:[
            [{Symbol:"A",Position:[0,0]},{Symbol:"A",Position:[1,0]},{Symbol:"A",Position:[2,3]},{Symbol:"A",Position:[3,3]},{Symbol:"W",Position:[4,0]}],
            [{Symbol:"Q",Position:[0,2]},{Symbol:"Q",Position:[1,1]},{Symbol:"Q",Position:[2,2]}]
        ],
        GrossWin:93,
        Anti:0
    },
    {
        Reels:reels2,
        Wins:[
            [{Symbol:"P3",Position:[0,0]},{Symbol:"W",Position:[1,0]}],
            [{Symbol:"P3",Position:[0,2]},{Symbol:"W",Position:[1,0]}],
            [{Symbol:"P4",Position:[0,1]},{Symbol:"W",Position:[1,0]},{Symbol:"P4",Position:[2,3]}],
            [{Symbol:"P2",Position:[0,3]},{Symbol:"W",Position:[1,0]},{Symbol:"P2",Position:[2,1]},{Symbol:"P2",Position:[3,2]},{Symbol:"P2",Position:[4,3]}]
        ],
        GrossWin:400,
        Anti:0
    },
    {
        Reels:reels3,
        Wins:[
            [{Symbol:"P2",Position:[0,0]},{Symbol:"P2",Position:[1,0]},{Symbol:"P2",Position:[2,3]}],
            [{Symbol:"P1",Position:[0,2]},{Symbol:"P1",Position:[1,1]}]
        ],
        GrossWin:150,
        Anti:0
    },
    {
        Reels:reels1,
        Wins:null,
        GrossWin:0,
        Anti:0
    },
];